export const FETCHING_BOOKS = 'FETCHING_BOOKS';
export const FETCHING_MORE_BOOKS = 'FETCHING_MORE_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_IS_LOGGED_IN_LOADING = 'SET_IS_LOGGED_IN_LOADING';
