export const FETCHING_BOOKS = 'FETCHING_BOOKS';
export const FETCHING_MORE_BOOKS = 'FETCHING_MORE_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
